os: Visual Studio 2017

install:
  # Download .NET CLI 1.1.1
  - ps: $url = "https://go.microsoft.com/fwlink/?linkid=843454"

   # Download .NET Core SDK and add to PATH
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFile = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: gitversion /output buildserver
  - ps: .\Update-Version.ps1 $env:GitVersion_NuGetVersion
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build /p:Configuration=Release .\test\SourceCodeSerializer.Test

after_build:
  - ps: dotnet pack .\src\SourceCodeSerializer -o ..\.. -c Release

test_script:
  - cmd: dotnet test /p:Configuration=Release .\test\SourceCodeSerializer.Test\SourceCodeSerializer.Test.csproj

artifacts:
  - path: '*.nupkg'
    name: NuGetArtifacts

deploy:
  provider: NuGet
  server: https://www.myget.org/F/source-code-serializer/api/v2/package
  api_key:
    secure: il1wdXL6HbnB8b6+T4PbKzkSVVg0GhCodYb1/jLqbQLH3qeqnvBlUfQv0J1x8GAA
  skip_symbols: false
  symbol_server: https://www.myget.org/F/source-code-serializer/symbols/api/v2/package
  artifact: /.*\.nupkg/